
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  notify-slack:
    image: plugins/slack
    secrets:
      - product_slack_url
    webhook: ${PRODUCT_SLACK_URL}
    username: drone
    template: "Testing. Pls ignore"
 
