
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  notify-slack:
    image: plugins/slack
    secrets:
      - product_slack_url
    webhook: https://hooks.slack.com/services/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
    username: drone
    template: "Testing. Pls ignore"
 
